### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by tanay1337** [Diksha-Rathi/find-my-place#2]
This repo is missing a license (even though you have mentioned that the project is MIT licensed in `README.md`). Without a license, all code is copyright to the author and may not be used by anyone else.

**Comment by Diksha-Rathi** [comment]
Hey, Tanay! I do have a License file in the repository. [This](https://github.com/Diksha-Rathi/find-my-place/blob/master/LICENSE) is the link.

**Comment by tanay1337** [comment]
@Diksha-Rathi This will solve the issue: https://github.com/Diksha-Rathi/find-my-place/pull/3

**Comment by Diksha-Rathi** [comment]
Thank you! Next time, I will definitely take care of this issue.

**Comment by tanay1337** [comment]
@Diksha-Rathi No problem!
