### ISSUE TITLE
Question: Results aren't sorted by distance from my current location?

### ISSUE THREAD

**Issue by sahildua2305** [Diksha-Rathi/find-my-place#4]

**Comment by Diksha-Rathi** [comment]
Yes, the list is rather displayed based on the rating of the search results.

**Comment by sahildua2305** [comment]
Shouldn't it show the results according to distance from my current location? Is it possible?

Ideally, I don't care about the ratings of the fire station if it's 25kms away from my place and there are other fire stations nearby me.

**Comment by Diksha-Rathi** [comment]
I tried but the results were not turning out to be very accurate. 

Also, if we consider the fact that at times it may happen that although a place might be a few kilometres away but it might be far better than the nearest one (say a restaurant). 

So, the decision to got with results sorted in order of ratings was kind of a work- around (considering the above two problems) such that the best possible results are displayed within the radius of 10 kilometres.

**Comment by sahildua2305** [comment]
Fair enough :+1:
